# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

#Site
title: JerryC
subtitle: 今日事,今日畢
description: 今日事,今日畢
keywords: Jerry,JerryC,blog,安卓博客,安卓,程序员,个人博客,安卓開發,安卓博客,程序員,安卓開發,個人博客,Android
author: JerryC
language: zh-TW
timezone: Asia/Hong_Kong
email: hwy0127@gmail.com

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://jerryc.me/
root: /
# permalink: :year/:month/:day/:title/
permalink: posts/:abbrlink/

# abbrlink config
abbrlink:
  alg: crc32  #support crc16(default) and crc32
  rep: hex    #support dec(default) and hex
  
# permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - 404.html
  - README.md
  - image/pwa/manifest.json

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true
  field: post
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

meta_generator: false

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: Butterfly
# theme: melody


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: git
    repo: 
      github: git@github.com:jerryc127/jerryc127.github.io.git
      coding: git@git.coding.net:jerry_c/jerry_c.coding.me.git
    branch: master
  # other deployer



#hexo sitemap
sitemap:
  path: sitemap.xml
  rel: true

baidusitemap:
  path: baidusitemap.xml



feed:
  type: atom
  path: atom.xml
  limit: 100

aplayer:
  meting: true


search:
  path: search.xml
  field: post
  content: true


# algolia:
#   applicationID: '502RMOS83O'
#   apiKey: 'c0621f18b83bdbdec63c1ac56235a5ea'
#   indexName: 'Jerryc'

nofollow:
  enable: true
  field: site
  exclude:

encrypt: # hexo-blog-encrypt
  abstract: Here's something encrypted, password is required to continue reading.
  message: Hey, password is required here.
  template: <div id="hexo-blog-encrypt" data-wpm="{{hbeWrongPassMessage}}" data-whm="{{hbeWrongHashMessage}}"><div class="hbe-input-container"><input type="password" id="hbePass" placeholder="{{hbeMessage}}" /><label>{{hbeMessage}}</label><div class="bottom-line"></div></div><script id="hbeData" type="hbeData" data-hmacdigest="{{hbeHmacDigest}}">{{hbeEncryptedData}}</script></div>
  wrong_pass_message: Oh, this is an invalid password. Check and try again, please.
  wrong_hash_message: Oh, these decrypted content cannot be verified, but you can still have a look.

douban:
  user: iamjerryc
  builtin: false
  movie:
    title: '那些年,我看過的電影'
    quote: '過去、現在、未來'
  timeout: 10000 

